#!/bin/bash

after_upgrade() {

if [ ! -d /etc/hdfscleaner ]
then
	mkdir -p /etc/hdfscleaner
fi

ln -s /usr/lib/python2.7/dist-packages/hdfscleaner/conf /etc/hdfscleaner/conf.d

}

after_install() {

if [ ! -d /etc/hdfscleaner ]
then
    echo "Make /etc/hdfscleaner..."
	mkdir -p /etc/hdfscleaner && echo " ...OK"
fi

if [ ! -d /var/log/hdfscleaner ]; then
    echo "Make /var/log/hdfscleaner..."
    mkdir /var/log/hdfscleaner && echo " ...OK"
fi

ln -s /usr/lib/python2.7/dist-packages/hdfscleaner/conf /etc/hdfscleaner/conf.d

echo -e "Install PostgreSQL python client..."
pip install psycopg2
pip install psycopg2-binary

echo -e "Install HDFS client..."
pip install hdfs

}

if [ "${1}" = "configure" -a -z "${2}" ] || \
   [ "${1}" = "abort-remove" ]
then
    # "after install" here
    # "abort-remove" happens when the pre-removal script failed.
    #   In that case, this script, which should be idemptoent, is run
    #   to ensure a clean roll-back of the removal.
    after_install
elif [ "${1}" = "configure" -a -n "${2}" ]
then
    upgradeFromVersion="${2}"
    # "after upgrade" here
    # NOTE: This slot is also used when deb packages are removed,
    # but their config files aren't, but a newer version of the
    # package is installed later, called "Config-Files" state.
    # basically, that still looks a _lot_ like an upgrade to me.
    after_upgrade "${2}"
elif echo "${1}" | grep -E -q "(abort|fail)"
then
    echo "Failed to install before the post-installation script was run." >&2
    exit 1
fi
